### PR TITLE
Chore: Initial React client setup

### PR DESCRIPTION
**Pull request by its-yashwanth-n**
Changes:

1. Setup client folder with react and material UI.
2. Added some naming conventions we can use.
3. Created folder structure and config files for eslint and prettier.
4. Added some required normal and dev packages.

### CODE REVIEW

**Comment by edwnl** [comment]
@its-yashwanth-n can we delete all the default files like react.svg etc. to just strip it down to barebones and build back up?

**Comment by its-yashwanth-n** [comment]
Hey @edwnl, Yup will remove the unnecessary files while I do the basic pages.

**Comment by its-yashwanth-n** [comment]
Will do that as part of another PR if you want to merge so that others can access it right away.

**Comment by edwnl** [comment]
another pr should be good, would like to get started asap thanks yash!!

**Pull request merged**
